# config/local-settings.yaml
# local develeopment configuration
application_port: 8000
database:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "postgres"
  database_name: "newsletter"
  require_ssl: false
